name: Deploy Static Website to S3

on:
  push:
    branches:
      - master  # Deploy on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to the latest version

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2  # Updated to the latest version
        with:
          terraform_version: 1.5.0  # Use a valid Terraform version

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2  # Updated to the latest version
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2  # Set to your region

      - name: Initialize Terraform
        working-directory: ./terraform
        run: terraform init

      - name: Apply Terraform
        working-directory: ./terraform
        run: terraform apply -auto-approve

      - name: Output Website URL
        run: |
          echo "Your website is available at http://your-bucket-name.s3-website-us-east-2.amazonaws.com"
