name: Deploy and Manage Static Website to S3

on:
  push:
    branches:
      - master          # Deploy on push to the master branch
    tags:
      - 'delete-*'      # Trigger deletion on push to tags matching 'delete-*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Initialize Terraform
        working-directory: ./terraform
        run: terraform init

      - name: Apply Terraform
        working-directory: ./terraform
        run: terraform apply -auto-approve

      - name: Output Website URL
        working-directory: ./terraform
        id: terraform
        run: |
          website_url=$(terraform output -raw website_url)
          echo "Your website is available at $website_url"

  destroy:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/delete-') # Trigger deletion if the ref starts with 'delete-'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Initialize Terraform
        working-directory: ./terraform
        run: terraform init

      - name: Destroy Terraform
        working-directory: ./terraform
        run: terraform destroy -auto-approve
